# Default values for kswp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: bansikah22/kswp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

schedule: "0 3 * * *"

# Configure the command and arguments for the kswp container.
# This allows you to customize the behavior of the cronjob.
#
# For example, to scan for all unused resources in a specific namespace:
# args:
#   - "scan"
#   - "--namespace"
#   - "my-namespace"
#
# To clean only unused configmaps and secrets:
# args:
#   - "clean"
#   - "--configmaps"
#   - "--secrets"
#
# To clean expired resources based on the `cleaner/ttl` annotation:
# args:
#   - "clean"
#   - "--ttl"
#
# The default is to sweep all unused resources.
args:
  - "sweep"
  - "--all"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  # Specifies whether RBAC resources should be created
  create: true
  # The name of the role to create.
  # If not set and create is true, a name is generated using the fullname template
  roleName: ""
  # The name of the role binding to create.
  # If not set and create is true, a name is generated using the fullname template
  roleBindingName: ""
